// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgbXQhUq30LbeDGp35KNEkHEfRNjD8E9s',
    appId: '1:848061712303:web:e7eca966b61a97b60d915a',
    messagingSenderId: '848061712303',
    projectId: 'notify-8f611',
    authDomain: 'notify-8f611.firebaseapp.com',
    storageBucket: 'notify-8f611.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKO-1UkgXavAKGte3ryUNuINSu_B0EoSU',
    appId: '1:848061712303:android:2cd837dd86cd8cd60d915a',
    messagingSenderId: '848061712303',
    projectId: 'notify-8f611',
    storageBucket: 'notify-8f611.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLcf7kLUVv3vjhrVDKKTLb9XYPiCK3p-k',
    appId: '1:848061712303:ios:f0f1921389309c3c0d915a',
    messagingSenderId: '848061712303',
    projectId: 'notify-8f611',
    storageBucket: 'notify-8f611.appspot.com',
    iosBundleId: 'com.example.firenotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLcf7kLUVv3vjhrVDKKTLb9XYPiCK3p-k',
    appId: '1:848061712303:ios:f0f1921389309c3c0d915a',
    messagingSenderId: '848061712303',
    projectId: 'notify-8f611',
    storageBucket: 'notify-8f611.appspot.com',
    iosBundleId: 'com.example.firenotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgbXQhUq30LbeDGp35KNEkHEfRNjD8E9s',
    appId: '1:848061712303:web:07c3a7e2b51ccd070d915a',
    messagingSenderId: '848061712303',
    projectId: 'notify-8f611',
    authDomain: 'notify-8f611.firebaseapp.com',
    storageBucket: 'notify-8f611.appspot.com',
  );
}
